### ISSUE TITLE
gnome 45 support

### ISSUE THREAD

**Issue by LuceLoong** [lyrahgames/gnome-extension-glasa#3]
Hi, today I received the GNOME 45 update via the Arch repo, but I found that the extension doesn't support it yet. Please add GNOME 45 support.

Thanks for this great extension!

**Comment by shizhangsz** [comment]
Hi, today I received the GNOME 45 update via the Arch repo, but I found that the extension doesn't support it yet. Please add GNOME 45 support.

Thanks for this great extension!

**Comment by lyrahgames** [comment]
> Hi, today I received the GNOME 45 update via the Arch repo, but I found that the extension doesn't support it yet. Please add GNOME 45 support.

Yes, I have it on my to-do list and already started to port it to the newest GNOME version.
I will further look into over the course of the next week.

> Thanks for this great extension!

You are very welcome. Nice to hear that you like it.

**Comment by lyrahgames** [comment]
Sorry, I did not assume that I would not be available for so long.
Thanks to @pinselimo for updating the extension to support GNOME 45.
For your information: I have uploaded the new extension version and hopefully it will be available for your system soon.

**Comment by LuceLoong** [comment]
> Sorry, I did not assume that I would not be available for so long.
> Thanks to @pinselimo for updating the extension to support GNOME 45.
> For your information: I have uploaded the new extension version and hopefully it will be available for your system soon.

Thank you again for your efforts
